Repository mhdzumair/MediaFusion, pull requests merged in 2023-10, with the labels that each got.

#12 Add support for selecting catalogs instead of languages & Update UI layout design for configure & home page
  api/main.py
  beamup.json
  db/schemas.py
  resources/css/styles.css
  resources/html/configure.html
  resources/html/home.html
  resources/js/config_script.js
  resources/manifest.json
  utils/const.py
  utils/parser.py
  utils/site_data.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#13 Add support for filtering streams based on user selected catalogs
  beamup.json
  utils/parser.py
Labels: hacktoberfest, feature, hacktoberfest-accepted

#16 Raal-Debrid: Add support for checking cached streams & delete magnet error torrents & bug fixes
  beamup.json
  db/crud.py
  db/models.py
  resources/manifest.json
  streaming_providers/realdebrid/client.py
  streaming_providers/realdebrid/utils.py
  utils/parser.py
Labels: bug, hacktoberfest, feature, hacktoberfest-accepted

#17 seedr: add function for free up space before downloading
  api/main.py
  beamup.json
  resources/manifest.json
  streaming_providers/seedr/utils.py
  utils/parser.py
  utils/torrent.py
Labels: enhancement, hacktoberfest

#21 DebridLink support initial commit
  api/main.py
  db/schemas.py
  resources/html/configure.html
  resources/js/config_script.js
  streaming_providers/debridlink/__init__.py
  streaming_providers/debridlink/api.py
  streaming_providers/debridlink/client.py
  streaming_providers/debridlink/utils.py
Labels: hacktoberfest, feature, hacktoberfest-accepted

#24 Add TamilMV scrapper script & bugfixes on TamilBlasters script
  resources/manifest.json
  scrappers/README.md
  scrappers/helpers.py
  scrappers/tamil_blasters.py
  scrappers/tamilmv.py
  utils/const.py
Labels: documentation, hacktoberfest, feature

#27 capture premium account exception for RD & DL
  beamup.json
  resources/exceptions/need_premium.mp4
  streaming_providers/debridlink/client.py
  streaming_providers/realdebrid/client.py
  utils/exception_video.py
Labels: bug

#34 Create README.md
  streaming_providers/realdebrid/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
